# Generated by Django 3.2.16 on 2023-01-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230114_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
