# Generated by Django 3.2.16 on 2023-01-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_ipaddress_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counted_views',
        ),
    ]
