# Generated by Django 3.2.16 on 2023-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AddField(
            model_name='post',
            name='counted_view',
            field=models.IntegerField(default=0),
        ),
    ]
